# Generated by Django 5.2.17 on 2026-09-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('voice_id', models.CharField(default='21m00Tcm4TlvDq8ikWAM', max_length=64)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_cache/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
